name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_verification_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Build verification
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Compile project
        run: npm run ci:build
      - name: Check formatting
        run: npm run check-all
      - name: Lint project
        run: npm run lint
      - name: Test project
        run: npm run ci:unit

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MUSHROOM_0F2425903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_build_command: npm run cd:build
          app_location: '/'
          api_location: '' # Not planned yet
          output_location: 'dist/agari-kai'

  deployment_verification_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs: build_and_deploy_job
    runs-on: ubuntu-latest
    name: Deployment verification
    env:
      CYPRESS_BASE_URL: ${{ needs.build_and_deploy_job.outputs.static_web_app_url }}/
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v4
        with:
          record: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MUSHROOM_0F2425903 }}
          action: 'close'
